### ISSUE TITLE
Жалоба на возможный баг szf режима с возможностью игры за зомби с оружием.

### ISSUE THREAD

**Issue by Strogon** [multimode-tf/Freak-n-Slender-Issues#1]
**Опишите баг**
Заметил как человек использовал оружие в szf во время игры за зомби и при спавне за выживших выдавал себе оружие не доступное в начале игры за них при этом без дэбаффов.

**Дополнительные заметки**
Использовал их человек из германии с ником cheese и с аватаркой сыра на сервере szf Flux.TF.

**Comment by 54xj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zombie Apocalyps | Зомби Апокалипсис](https://trello.com/c/dfgV5N5E/16-zombie-apocalyps-%D0%B7%D0%BE%D0%BC%D0%B1%D0%B8-%D0%B0%D0%BF%D0%BE%D0%BA%D0%B0%D0%BB%D0%B8%D0%BF%D1%81%D0%B8%D1%81)

**Comment by 54xj** [comment]
Режим был убран, следовательно, нет смысла искать и пробовать решить данный баг.
