### ISSUE TITLE
Игроки с отображаемым уровнем "Что-то сломалось"

### ISSUE THREAD

**Issue by 54xj** [multimode-tf/Freak-n-Slender-Issues#3]
Заметил, что у некоторых игроков вместо уровня отображается "Что-то сломалось...". Такое происходит, если плагин с инфой о игроке в худе не получает уровень от игрока/не удаётся прочитать список уровней. Самое интересное, что у кого-то уровни отображаются нормально, а у кого-то как раз "Что-то сломалось..."

**Comment by saxybois** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Баги системных плагинов](https://trello.com/c/LETnJ1Hg/66-%D0%B1%D0%B0%D0%B3%D0%B8-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%BD%D1%8B%D1%85-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D0%BE%D0%B2)

**Comment by saxybois** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Системные плагины](https://trello.com/c/TnNmk8HV/23-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%BD%D1%8B%D0%B5-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D1%8B)

**Comment by saxybois** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [HUD Player](https://trello.com/c/WeAKn2uW/67-hud-player)

**Comment by 54xj** [comment]
Пофикшено.
